FROM golang:1.21-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

# Install a specific version of air compatible with Go 1.21
RUN go install github.com/cosmtrek/air@v1.49.0

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Use air to run the application
CMD ["air"]